<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Kewarganegaraan;

class KewarganegaraanSeeder extends Seeder
{
    public function run(): void
    {
        Kewarganegaraan::truncate();

        $negara = [
            ['nama_negara' => 'Afghanistan',                      'kode_negara' => 'AF'],
            ['nama_negara' => 'Afrika Selatan',                   'kode_negara' => 'ZA'],
            ['nama_negara' => 'Albania',                          'kode_negara' => 'AL'],
            ['nama_negara' => 'Aljazair',                         'kode_negara' => 'DZ'],
            ['nama_negara' => 'Amerika Serikat',                  'kode_negara' => 'US'],
            ['nama_negara' => 'Andorra',                          'kode_negara' => 'AD'],
            ['nama_negara' => 'Angola',                           'kode_negara' => 'AO'],
            ['nama_negara' => 'Antigua dan Barbuda',              'kode_negara' => 'AG'],
            ['nama_negara' => 'Arab Saudi',                       'kode_negara' => 'SA'],
            ['nama_negara' => 'Argentina',                        'kode_negara' => 'AR'],
            ['nama_negara' => 'Armenia',                          'kode_negara' => 'AM'],
            ['nama_negara' => 'Australia',                        'kode_negara' => 'AU'],
            ['nama_negara' => 'Austria',                          'kode_negara' => 'AT'],
            ['nama_negara' => 'Azerbaijan',                       'kode_negara' => 'AZ'],
            ['nama_negara' => 'Bahama',                           'kode_negara' => 'BS'],
            ['nama_negara' => 'Bahrain',                          'kode_negara' => 'BH'],
            ['nama_negara' => 'Bangladesh',                       'kode_negara' => 'BD'],
            ['nama_negara' => 'Barbados',                         'kode_negara' => 'BB'],
            ['nama_negara' => 'Belanda',                          'kode_negara' => 'NL'],
            ['nama_negara' => 'Belarus',                          'kode_negara' => 'BY'],
            ['nama_negara' => 'Belgia',                           'kode_negara' => 'BE'],
            ['nama_negara' => 'Belize',                           'kode_negara' => 'BZ'],
            ['nama_negara' => 'Benin',                            'kode_negara' => 'BJ'],
            ['nama_negara' => 'Bhutan',                           'kode_negara' => 'BT'],
            ['nama_negara' => 'Bolivia',                          'kode_negara' => 'BO'],
            ['nama_negara' => 'Bosnia dan Herzegovina',           'kode_negara' => 'BA'],
            ['nama_negara' => 'Botswana',                         'kode_negara' => 'BW'],
            ['nama_negara' => 'Brazil',                           'kode_negara' => 'BR'],
            ['nama_negara' => 'Brunei Darussalam',                'kode_negara' => 'BN'],
            ['nama_negara' => 'Bulgaria',                         'kode_negara' => 'BG'],
            ['nama_negara' => 'Burkina Faso',                     'kode_negara' => 'BF'],
            ['nama_negara' => 'Burundi',                          'kode_negara' => 'BI'],
            ['nama_negara' => 'Chad',                             'kode_negara' => 'TD'],
            ['nama_negara' => 'Chili',                            'kode_negara' => 'CL'],
            ['nama_negara' => 'China',                            'kode_negara' => 'CN'],
            ['nama_negara' => 'Denmark',                          'kode_negara' => 'DK'],
            ['nama_negara' => 'Djibouti',                         'kode_negara' => 'DJ'],
            ['nama_negara' => 'Dominika',                         'kode_negara' => 'DM'],
            ['nama_negara' => 'Ekuador',                          'kode_negara' => 'EC'],
            ['nama_negara' => 'El Salvador',                      'kode_negara' => 'SV'],
            ['nama_negara' => 'Eritrea',                          'kode_negara' => 'ER'],
            ['nama_negara' => 'Estonia',                          'kode_negara' => 'EE'],
            ['nama_negara' => 'Eswatini',                         'kode_negara' => 'SZ'],
            ['nama_negara' => 'Ethiopia',                         'kode_negara' => 'ET'],
            ['nama_negara' => 'Fiji',                             'kode_negara' => 'FJ'],
            ['nama_negara' => 'Filipina',                         'kode_negara' => 'PH'],
            ['nama_negara' => 'Finlandia',                        'kode_negara' => 'FI'],
            ['nama_negara' => 'Gabon',                            'kode_negara' => 'GA'],
            ['nama_negara' => 'Gambia',                           'kode_negara' => 'GM'],
            ['nama_negara' => 'Georgia',                          'kode_negara' => 'GE'],
            ['nama_negara' => 'Ghana',                            'kode_negara' => 'GH'],
            ['nama_negara' => 'Grenada',                          'kode_negara' => 'GD'],
            ['nama_negara' => 'Guatemala',                        'kode_negara' => 'GT'],
            ['nama_negara' => 'Guinea',                           'kode_negara' => 'GN'],
            ['nama_negara' => 'Guinea Khatulistiwa',              'kode_negara' => 'GQ'],
            ['nama_negara' => 'Guinea-Bissau',                    'kode_negara' => 'GW'],
            ['nama_negara' => 'Guyana',                           'kode_negara' => 'GY'],
            ['nama_negara' => 'Haiti',                            'kode_negara' => 'HT'],
            ['nama_negara' => 'Honduras',                         'kode_negara' => 'HN'],
            ['nama_negara' => 'Hongaria',                         'kode_negara' => 'HU'],
            ['nama_negara' => 'India',                            'kode_negara' => 'IN'],
            ['nama_negara' => 'Inggris',                          'kode_negara' => 'GB'],
            ['nama_negara' => 'Irak',                             'kode_negara' => 'IQ'],
            ['nama_negara' => 'Iran',                             'kode_negara' => 'IR'],
            ['nama_negara' => 'Irlandia',                         'kode_negara' => 'IE'],
            ['nama_negara' => 'Islandia',                         'kode_negara' => 'IS'],
            ['nama_negara' => 'Israel',                           'kode_negara' => 'IL'],
            ['nama_negara' => 'Italia',                           'kode_negara' => 'IT'],
            ['nama_negara' => 'Jamaika',                          'kode_negara' => 'JM'],
            ['nama_negara' => 'Jepang',                           'kode_negara' => 'JP'],
            ['nama_negara' => 'Jerman',                           'kode_negara' => 'DE'],
            ['nama_negara' => 'Yordania',                         'kode_negara' => 'JO'],
            ['nama_negara' => 'Kamboja',                          'kode_negara' => 'KH'],
            ['nama_negara' => 'Kamerun',                          'kode_negara' => 'CM'],
            ['nama_negara' => 'Kanada',                           'kode_negara' => 'CA'],
            ['nama_negara' => 'Kazakhstan',                       'kode_negara' => 'KZ'],
            ['nama_negara' => 'Kenya',                            'kode_negara' => 'KE'],
            ['nama_negara' => 'Kepulauan Marshall',               'kode_negara' => 'MH'],
            ['nama_negara' => 'Kepulauan Solomon',                'kode_negara' => 'SB'],
            ['nama_negara' => 'Kiribati',                         'kode_negara' => 'KI'],
            ['nama_negara' => 'Kolombia',                         'kode_negara' => 'CO'],
            ['nama_negara' => 'Komoro',                           'kode_negara' => 'KM'],
            ['nama_negara' => 'Kongo',                            'kode_negara' => 'CG'],
            ['nama_negara' => 'Korea Selatan',                    'kode_negara' => 'KR'],
            ['nama_negara' => 'Korea Utara',                      'kode_negara' => 'KP'],
            ['nama_negara' => 'Kosovo',                           'kode_negara' => 'XK'],
            ['nama_negara' => 'Kosta Rika',                       'kode_negara' => 'CR'],
            ['nama_negara' => 'Kroasia',                          'kode_negara' => 'HR'],
            ['nama_negara' => 'Kuba',                             'kode_negara' => 'CU'],
            ['nama_negara' => 'Kuwait',                           'kode_negara' => 'KW'],
            ['nama_negara' => 'Kyrgyzstan',                       'kode_negara' => 'KG'],
            ['nama_negara' => 'Laos',                             'kode_negara' => 'LA'],
            ['nama_negara' => 'Latvia',                           'kode_negara' => 'LV'],
            ['nama_negara' => 'Lebanon',                          'kode_negara' => 'LB'],
            ['nama_negara' => 'Lesotho',                          'kode_negara' => 'LS'],
            ['nama_negara' => 'Liberia',                          'kode_negara' => 'LR'],
            ['nama_negara' => 'Libya',                            'kode_negara' => 'LY'],
            ['nama_negara' => 'Liechtenstein',                    'kode_negara' => 'LI'],
            ['nama_negara' => 'Lithuania',                        'kode_negara' => 'LT'],
            ['nama_negara' => 'Luksemburg',                       'kode_negara' => 'LU'],
            ['nama_negara' => 'Madagaskar',                       'kode_negara' => 'MG'],
            ['nama_negara' => 'Maladewa',                         'kode_negara' => 'MV'],
            ['nama_negara' => 'Malawi',                           'kode_negara' => 'MW'],
            ['nama_negara' => 'Malaysia',                         'kode_negara' => 'MY'],
            ['nama_negara' => 'Mali',                             'kode_negara' => 'ML'],
            ['nama_negara' => 'Malta',                            'kode_negara' => 'MT'],
            ['nama_negara' => 'Maroko',                           'kode_negara' => 'MA'],
            ['nama_negara' => 'Mauritania',                       'kode_negara' => 'MR'],
            ['nama_negara' => 'Mauritius',                        'kode_negara' => 'MU'],
            ['nama_negara' => 'Meksiko',                          'kode_negara' => 'MX'],
            ['nama_negara' => 'Mesir',                            'kode_negara' => 'EG'],
            ['nama_negara' => 'Mikronesia',                       'kode_negara' => 'FM'],
            ['nama_negara' => 'Moldova',                          'kode_negara' => 'MD'],
            ['nama_negara' => 'Monako',                           'kode_negara' => 'MC'],
            ['nama_negara' => 'Mongolia',                         'kode_negara' => 'MN'],
            ['nama_negara' => 'Montenegro',                       'kode_negara' => 'ME'],
            ['nama_negara' => 'Mozambik',                         'kode_negara' => 'MZ'],
            ['nama_negara' => 'Myanmar',                          'kode_negara' => 'MM'],
            ['nama_negara' => 'Namibia',                          'kode_negara' => 'NA'],
            ['nama_negara' => 'Nauru',                            'kode_negara' => 'NR'],
            ['nama_negara' => 'Nepal',                            'kode_negara' => 'NP'],
            ['nama_negara' => 'Niger',                            'kode_negara' => 'NE'],
            ['nama_negara' => 'Nigeria',                          'kode_negara' => 'NG'],
            ['nama_negara' => 'Nikaragua',                        'kode_negara' => 'NI'],
            ['nama_negara' => 'Norwegia',                         'kode_negara' => 'NO'],
            ['nama_negara' => 'Oman',                             'kode_negara' => 'OM'],
            ['nama_negara' => 'Pakistan',                         'kode_negara' => 'PK'],
            ['nama_negara' => 'Palau',                            'kode_negara' => 'PW'],
            ['nama_negara' => 'Palestina',                        'kode_negara' => 'PS'],
            ['nama_negara' => 'Panama',                           'kode_negara' => 'PA'],
            ['nama_negara' => 'Papua Nugini',                     'kode_negara' => 'PG'],
            ['nama_negara' => 'Paraguay',                         'kode_negara' => 'PY'],
            ['nama_negara' => 'Peru',                             'kode_negara' => 'PE'],
            ['nama_negara' => 'Polandia',                         'kode_negara' => 'PL'],
            ['nama_negara' => 'Portugal',                         'kode_negara' => 'PT'],
            ['nama_negara' => 'Prancis',                          'kode_negara' => 'FR'],
            ['nama_negara' => 'Qatar',                            'kode_negara' => 'QA'],
            ['nama_negara' => 'Republik Afrika Tengah',           'kode_negara' => 'CF'],
            ['nama_negara' => 'Republik Ceko',                    'kode_negara' => 'CZ'],
            ['nama_negara' => 'Republik Dominika',                'kode_negara' => 'DO'],
            ['nama_negara' => 'Republik Kongo',                   'kode_negara' => 'CD'],
            ['nama_negara' => 'Romania',                          'kode_negara' => 'RO'],
            ['nama_negara' => 'Rusia',                            'kode_negara' => 'RU'],
            ['nama_negara' => 'Rwanda',                           'kode_negara' => 'RW'],
            ['nama_negara' => 'Saint Kitts dan Nevis',            'kode_negara' => 'KN'],
            ['nama_negara' => 'Saint Lucia',                      'kode_negara' => 'LC'],
            ['nama_negara' => 'Saint Vincent dan Grenadines',     'kode_negara' => 'VC'],
            ['nama_negara' => 'Samoa',                            'kode_negara' => 'WS'],
            ['nama_negara' => 'San Marino',                       'kode_negara' => 'SM'],
            ['nama_negara' => 'Sao Tome dan Principe',            'kode_negara' => 'ST'],
            ['nama_negara' => 'Senegal',                          'kode_negara' => 'SN'],
            ['nama_negara' => 'Serbia',                           'kode_negara' => 'RS'],
            ['nama_negara' => 'Seychelles',                       'kode_negara' => 'SC'],
            ['nama_negara' => 'Sierra Leone',                     'kode_negara' => 'SL'],
            ['nama_negara' => 'Singapura',                        'kode_negara' => 'SG'],
            ['nama_negara' => 'Siprus',                           'kode_negara' => 'CY'],
            ['nama_negara' => 'Slovakia',                         'kode_negara' => 'SK'],
            ['nama_negara' => 'Slovenia',                         'kode_negara' => 'SI'],
            ['nama_negara' => 'Somalia',                          'kode_negara' => 'SO'],
            ['nama_negara' => 'Spanyol',                          'kode_negara' => 'ES'],
            ['nama_negara' => 'Sri Lanka',                        'kode_negara' => 'LK'],
            ['nama_negara' => 'Sudan',                            'kode_negara' => 'SD'],
            ['nama_negara' => 'Sudan Selatan',                    'kode_negara' => 'SS'],
            ['nama_negara' => 'Suriah',                           'kode_negara' => 'SY'],
            ['nama_negara' => 'Suriname',                         'kode_negara' => 'SR'],
            ['nama_negara' => 'Swedia',                           'kode_negara' => 'SE'],
            ['nama_negara' => 'Swiss',                            'kode_negara' => 'CH'],
            ['nama_negara' => 'Taiwan',                           'kode_negara' => 'TW'],
            ['nama_negara' => 'Tajikistan',                       'kode_negara' => 'TJ'],
            ['nama_negara' => 'Tanzania',                         'kode_negara' => 'TZ'],
            ['nama_negara' => 'Thailand',                         'kode_negara' => 'TH'],
            ['nama_negara' => 'Timor Leste',                      'kode_negara' => 'TL'],
            ['nama_negara' => 'Togo',                             'kode_negara' => 'TG'],
            ['nama_negara' => 'Tonga',                            'kode_negara' => 'TO'],
            ['nama_negara' => 'Trinidad dan Tobago',              'kode_negara' => 'TT'],
            ['nama_negara' => 'Tunisia',                          'kode_negara' => 'TN'],
            ['nama_negara' => 'Turki',                            'kode_negara' => 'TR'],
            ['nama_negara' => 'Turkmenistan',                     'kode_negara' => 'TM'],
            ['nama_negara' => 'Tuvalu',                           'kode_negara' => 'TV'],
            ['nama_negara' => 'Uganda',                           'kode_negara' => 'UG'],
            ['nama_negara' => 'Ukraina',                          'kode_negara' => 'UA'],
            ['nama_negara' => 'Uni Emirat Arab',                  'kode_negara' => 'AE'],
            ['nama_negara' => 'Uruguay',                          'kode_negara' => 'UY'],
            ['nama_negara' => 'Uzbekistan',                       'kode_negara' => 'UZ'],
            ['nama_negara' => 'Vanuatu',                          'kode_negara' => 'VU'],
            ['nama_negara' => 'Vatikan',                          'kode_negara' => 'VA'],
            ['nama_negara' => 'Venezuela',                        'kode_negara' => 'VE'],
            ['nama_negara' => 'Vietnam',                          'kode_negara' => 'VN'],
            ['nama_negara' => 'Yaman',                            'kode_negara' => 'YE'],
            ['nama_negara' => 'Yunani',                           'kode_negara' => 'GR'],
            ['nama_negara' => 'Zambia',                           'kode_negara' => 'ZM'],
            ['nama_negara' => 'Zimbabwe',                         'kode_negara' => 'ZW'],
            ['nama_negara' => 'Kap Verde',                        'kode_negara' => 'CV'],
            ['nama_negara' => 'Selandia Baru',                    'kode_negara' => 'NZ'],
            ['nama_negara' => 'Papua Barat',                      'kode_negara' => 'PW'],
            ['nama_negara' => 'Makedonia Utara',                  'kode_negara' => 'MK'],
            ['nama_negara' => 'Lainnya',                          'kode_negara' => 'OT'],
        ];

        foreach ($negara as $data) {
            Kewarganegaraan::create($data);
        }
    }
}